workflows:
    react-native-android:
        name: React Native Android
stages:
    - build
    - test
node: latest

triggering:
            events:
                - push
                - tag
                - pull_request
            branch_patterns:
                - pattern: develop
                  include: true
                  source: true
scripts:
       - name: Install npm dependencies
          script: |
               npm install
build:
    stage: build
    script:
        - echo "Building"
        - mkdir build
        - touch build/info.txt
    artifacts:
        paths:
            - build/

test:
    stage: test
    script:
        - echo "Testing"
        - test -f "build/info.txt"
